modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/LatvianModder/Jar-Mod/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "jarmod"
version = "${version}"
displayName = "Jar Mod"
authors = "LatvianModder"
description = '''
Adds Jars. Nothing else.
'''

[[dependencies.jarmod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jarmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"