modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Jar-Mod/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbjarmod"
version = "${version}"
displayName = "FTB Jar Mod"
authors = "LatvianModder"
description = '''
Adds Jars. Nothing else.
'''

[[dependencies.ftbjarmod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbjarmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"